
/* Drop Tables */

DROP TABLE CARTORDER CASCADE CONSTRAINTS;
DROP TABLE PRODUCT CASCADE CONSTRAINTS;
DROP TABLE REPLY CASCADE CONSTRAINTS;
DROP TABLE QNA CASCADE CONSTRAINTS;
DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE MENU CASCADE CONSTRAINTS;




/* Create Tables */

CREATE TABLE CARTORDER
(
	-- 장바구니주문번호
	CONO number NOT NULL,
	-- 아이디
	ID varchar2(50) NOT NULL,
	-- 게시글번호
	PNO number NOT NULL,
	-- 상품명
	PRONAME varchar2(300) NOT NULL,
	-- 수량
	QTY number NOT NULL,
	-- 제품가격
	PRICE number NOT NULL,
	-- 주문일자
	ORDERDATE date,
	ISORDER number DEFAULT 0,
	PRIMARY KEY (CONO)
);


CREATE TABLE MEMBER
(
	-- 아이디
	ID varchar2(50) NOT NULL,
	PWD varchar2(75) NOT NULL,
	-- 이메일
	EMAIL varchar2(60) NOT NULL,
	-- 사진
	PICTURE varchar2(200) DEFAULT 'noImage.jpg',
	-- 0: 정지계정 1:활성계정 2: 삭제계정
	ENABLED number DEFAULT 1,
	-- 가입일
	REGDATE date,
	-- 휴대폰번호
	PHONE varchar2(35) DEFAULT '01012345678',
	-- 이름
	NAME varchar2(20) DEFAULT '홍길동',
	REGISTER varchar2(50) DEFAULT 'super',
	-- 주소
	ADDRESS varchar2(200),
	-- 권한
	AUTHORITY varchar2(50) DEFAULT 'ROLE_USER',
	PRIMARY KEY (ID)
);


CREATE TABLE MENU
(
	-- 메뉴코드
	MCODE varchar2(30) NOT NULL,
	-- 메뉴명
	MNAME varchar2(40),
	-- 메뉴주소
	MURL varchar2(150),
	-- 메뉴아이콘
	MICON varchar2(100),
	-- 상위메뉴코드
	UPCODE varchar2(40) DEFAULT 'M000000',
	-- 1:네비게이션
	-- 0: 감춤
	ISNAV number,
	PRIMARY KEY (MCODE)
);


CREATE TABLE PRODUCT
(
	-- 게시글번호
	PNO number NOT NULL,
	-- 상품명
	PRONAME varchar2(300) NOT NULL,
	-- 가격
	PRICE number,
	-- 작성자
	WRITER varchar2(50) NOT NULL,
	-- 상품내용
	CONTENT varchar2(3200) NOT NULL,
	-- 상품사진
	PICTURE varchar2(200) DEFAULT 'noImage.jpg',
	-- 등록일
	REGDATE date,
	-- 수정일
	UPDATEDATE date,
	-- 조회수
	VIEWCNT number DEFAULT 0,
	-- 품절여부
	SOLDOUT varchar2(2) DEFAULT 'N',
	-- 삭제여부
	ISDEL varchar2(2) DEFAULT 'N',
	PRIMARY KEY (PNO)
);


CREATE TABLE QNA
(
	-- 게시글번호
	QNO number NOT NULL,
	-- 문의분류
	QTYPE varchar2(30),
	-- 제목
	TITLE varchar2(300) NOT NULL,
	-- 작성자
	WRITER varchar2(50) NOT NULL,
	-- 내용
	CONTENT varchar2(3200) NOT NULL,
	-- 첨부사진
	PICTURE varchar2(200),
	-- 작성일
	REGDATE date,
	-- 조회수
	VIEWCNT number DEFAULT 0,
	-- 답변여부
	ISANSWER varchar2(2) DEFAULT 'N',
	-- 삭제여부
	ISDEL varchar2(2) DEFAULT 'N',
	PRIMARY KEY (QNO)
);


CREATE TABLE REPLY
(
	-- 댓글번호
	RNO number NOT NULL,
	-- 게시글번호
	QNO number NOT NULL,
	-- 답변작성자
	REPLYER varchar2(50) NOT NULL,
	-- 답변내용
	REPLYTEXT varchar2(600) NOT NULL,
	-- 등록일
	REGDATE date,
	-- 수정일
	UPDATEDATE date,
	PRIMARY KEY (RNO)
);



/* Create Foreign Keys */

ALTER TABLE CARTORDER
	ADD FOREIGN KEY (ID)
	REFERENCES MEMBER (ID)
;


ALTER TABLE PRODUCT
	ADD FOREIGN KEY (WRITER)
	REFERENCES MEMBER (ID)
;


ALTER TABLE QNA
	ADD FOREIGN KEY (WRITER)
	REFERENCES MEMBER (ID)
;


ALTER TABLE REPLY
	ADD FOREIGN KEY (REPLYER)
	REFERENCES MEMBER (ID)
;


ALTER TABLE CARTORDER
	ADD FOREIGN KEY (PNO)
	REFERENCES PRODUCT (PNO)
;


ALTER TABLE REPLY
	ADD FOREIGN KEY (QNO)
	REFERENCES QNA (QNO)
;



/* Comments */

COMMENT ON COLUMN CARTORDER.CONO IS '장바구니주문번호';
COMMENT ON COLUMN CARTORDER.ID IS '아이디';
COMMENT ON COLUMN CARTORDER.PNO IS '게시글번호';
COMMENT ON COLUMN CARTORDER.PRONAME IS '상품명';
COMMENT ON COLUMN CARTORDER.QTY IS '수량';
COMMENT ON COLUMN CARTORDER.PRICE IS '제품가격';
COMMENT ON COLUMN CARTORDER.ORDERDATE IS '주문일자';
COMMENT ON COLUMN MEMBER.ID IS '아이디';
COMMENT ON COLUMN MEMBER.EMAIL IS '이메일';
COMMENT ON COLUMN MEMBER.PICTURE IS '사진';
COMMENT ON COLUMN MEMBER.ENABLED IS '0: 정지계정 1:활성계정 2: 삭제계정';
COMMENT ON COLUMN MEMBER.REGDATE IS '가입일';
COMMENT ON COLUMN MEMBER.PHONE IS '휴대폰번호';
COMMENT ON COLUMN MEMBER.NAME IS '이름';
COMMENT ON COLUMN MEMBER.ADDRESS IS '주소';
COMMENT ON COLUMN MEMBER.AUTHORITY IS '권한';
COMMENT ON COLUMN MENU.MCODE IS '메뉴코드';
COMMENT ON COLUMN MENU.MNAME IS '메뉴명';
COMMENT ON COLUMN MENU.MURL IS '메뉴주소';
COMMENT ON COLUMN MENU.MICON IS '메뉴아이콘';
COMMENT ON COLUMN MENU.UPCODE IS '상위메뉴코드';
COMMENT ON COLUMN MENU.ISNAV IS '1:네비게이션
0: 감춤';
COMMENT ON COLUMN PRODUCT.PNO IS '게시글번호';
COMMENT ON COLUMN PRODUCT.PRONAME IS '상품명';
COMMENT ON COLUMN PRODUCT.PRICE IS '가격';
COMMENT ON COLUMN PRODUCT.WRITER IS '작성자';
COMMENT ON COLUMN PRODUCT.CONTENT IS '상품내용';
COMMENT ON COLUMN PRODUCT.PICTURE IS '상품사진';
COMMENT ON COLUMN PRODUCT.REGDATE IS '등록일';
COMMENT ON COLUMN PRODUCT.UPDATEDATE IS '수정일';
COMMENT ON COLUMN PRODUCT.VIEWCNT IS '조회수';
COMMENT ON COLUMN PRODUCT.SOLDOUT IS '품절여부';
COMMENT ON COLUMN PRODUCT.ISDEL IS '삭제여부';
COMMENT ON COLUMN QNA.QNO IS '게시글번호';
COMMENT ON COLUMN QNA.QTYPE IS '문의분류';
COMMENT ON COLUMN QNA.TITLE IS '제목';
COMMENT ON COLUMN QNA.WRITER IS '작성자';
COMMENT ON COLUMN QNA.CONTENT IS '내용';
COMMENT ON COLUMN QNA.PICTURE IS '첨부사진';
COMMENT ON COLUMN QNA.REGDATE IS '작성일';
COMMENT ON COLUMN QNA.VIEWCNT IS '조회수';
COMMENT ON COLUMN QNA.ISANSWER IS '답변여부';
COMMENT ON COLUMN QNA.ISDEL IS '삭제여부';
COMMENT ON COLUMN REPLY.RNO IS '댓글번호';
COMMENT ON COLUMN REPLY.QNO IS '게시글번호';
COMMENT ON COLUMN REPLY.REPLYER IS '답변작성자';
COMMENT ON COLUMN REPLY.REPLYTEXT IS '답변내용';
COMMENT ON COLUMN REPLY.REGDATE IS '등록일';
COMMENT ON COLUMN REPLY.UPDATEDATE IS '수정일';



